{% set name = "jupyter-sysml-kernel" %}
{% set version = "2021-05a" %}
{% set sha256 = "c090d0bceb3a0207d0ad4841d4535f459f9be71c79036c773130bc9fdec64fc8" %}

package:
  name: {{ name|lower }}
  version: {{ version | replace("-", ".") }}

source:
  url: https://jitpack.io/com/github/Systems-Modeling/SysML-v2-Pilot-Implementation/{{ name }}/{{ version }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} ./install.py --api-base-path=http://sysml2.intercax.com:9000 --sys-prefix

requirements:
  host:
    - jupyter_client
    - python >=3.6
  run:
    - graphviz
    - jupyter_client
    - openjdk >=11
    - python >=3.6

test:
  requires:
    - jupyter_client
  commands:
    - conda list {{ name }}
    - jupyter kernelspec list

about:
  home: https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: 
    - LICENSE
    - LICENSE-GPL
  summary: 'SysML v2 Kernel for Jupyter'
  description: |
    An interactive SysML v2 shell and Jupyter kernel to work with
    SysML v2 models in Jupyter notebooks and other interactive frontends.
  dev_url: https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation

extra:
  recipe-maintainers:
    - ivan-gomes
