{% set name = "jupyter-sysml-kernel" %}
{% set semver = "0.48.0" %}
{% set calver = "2025-02" %}
{% set sha256 = "e9caa696de421c763c0d7c913b6fe5d492216369cea5064bc7a39f323c13dfa7" %}

package:
  name: {{ name|lower }}
  version: {{ semver }}

source:
  url: https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/releases/download/{{ calver }}/{{ name }}-{{ semver }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} ./install.py --api-base-path=http://sysml2.intercax.com:9000 --sys-prefix

requirements:
  host:
    - jupyter_client
    - python {{ python_min }}
  run:
    - graphviz
    - jupyter_client
    - openjdk >=17
    - python >={{ python_min }}

test:
  requires:
    - jupyter_client
    - python {{ python_min }}
  commands:
    - conda list {{ name }}
    - jupyter kernelspec list

about:
  home: https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: 
    - LICENSE
    - LICENSE-GPL
  summary: 'SysML v2 Kernel for Jupyter'
  description: |
    An interactive SysML v2 shell and Jupyter kernel to work with
    SysML v2 models in Jupyter notebooks and other interactive frontends.
  dev_url: https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation

extra:
  recipe-maintainers:
    - ivan-gomes
    - seidewitz
