{% set name = "jupyter-sysml-kernel" %}
{% set semver = "0.46.0" %}
{% set calver = "2024-11" %}
{% set sha256 = "eddfcd95d5a13a4c886d5a1007d2835ad0ef2bc66c91ea17cfeeb44e266f8385" %}

package:
  name: {{ name|lower }}
  version: {{ semver }}

source:
  url: https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/releases/download/{{ calver }}/{{ name }}-{{ semver }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} ./install.py --api-base-path=http://sysml2.intercax.com:9000 --sys-prefix

requirements:
  host:
    - jupyter_client
    - python >=3.6
  run:
    - graphviz
    - jupyter_client
    - openjdk >=17
    - python >=3.6

test:
  requires:
    - jupyter_client
  commands:
    - conda list {{ name }}
    - jupyter kernelspec list

about:
  home: https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: 
    - LICENSE
    - LICENSE-GPL
  summary: 'SysML v2 Kernel for Jupyter'
  description: |
    An interactive SysML v2 shell and Jupyter kernel to work with
    SysML v2 models in Jupyter notebooks and other interactive frontends.
  dev_url: https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation

extra:
  recipe-maintainers:
    - ivan-gomes
    - seidewitz
