{% set name = "jupyter-sysml-kernel" %}
{% set semver = "0.19.0" %}
{% set calver = "2021-12" %}
{% set sha256 = "45163a2827a8d138566fd19ddf94a506fe4696f714b40c86e419bf2fe5f6449b" %}

package:
  name: {{ name|lower }}
  version: {{ semver }}

source:
  url: https://jitpack.io/com/github/Systems-Modeling/SysML-v2-Pilot-Implementation/{{ name }}/{{ calver }}/{{ name }}-{{ calver }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} ./install.py --api-base-path=http://sysml2.intercax.com:9000 --sys-prefix

requirements:
  host:
    - jupyter_client
    - python >=3.6
  run:
    - graphviz
    - jupyter_client
    - openjdk >=11
    - python >=3.6

test:
  requires:
    - jupyter_client
  commands:
    - conda list {{ name }}
    - jupyter kernelspec list

about:
  home: https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: 
    - LICENSE
    - LICENSE-GPL
  summary: 'SysML v2 Kernel for Jupyter'
  description: |
    An interactive SysML v2 shell and Jupyter kernel to work with
    SysML v2 models in Jupyter notebooks and other interactive frontends.
  dev_url: https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation

extra:
  recipe-maintainers:
    - ivan-gomes
